studySpec:
  metrics:
    - metricId: myAccuracy
      goal: MAXIMIZE
  parameters:
    - parameterId: epochs
      integerValueSpec:
        minValue: 10
        maxValue: 50
    - parameterId: batch-size
      discreteValueSpec:
        values:
          - 1024
          - 2048
          - 4096
maxTrialCount: 100
parallelTrialCount: 4
trialJobSpec:
  workerPoolSpecs:
    machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    pythonPackageSpec:
      executorImageUri: europe-docker.pkg.dev/vertex-ai/training/tf-cpu.2-3:latest
      packageUris: gs://ml-in-the-cloud-vertex/dist/my_first_ml_model-0.4.tar.gz
      pythonModule: trainer.task
      args:
        - --job-dir=gs://ml-in-the-cloud-vertex/job_dir/

