steps:
  # Grab full history
  - name: gcr.io/cloud-builders/git
    args: [ 'fetch', '--unshallow' ]
  # Build package
  - name: python
    entrypoint: python
    dir: 'model_mlops_with_vertex'
    args: [ "setup.py", "sdist" ]
# Upload built package
artifacts:
  objects:
    location: 'gs://ihr-vertex-pipelines/dist/'
    paths: [ 'model_mlops_with_vertex/dist/*.tar.gz' ]