studySpec:
  metrics:
    - metricId: kschool_accuracy
      goal: MAXIMIZE
  parameters:
    - parameterId: epochs
      integerValueSpec:
        minValue: 10
        maxValue: 50
    - parameterId: batch-size
      discreteValueSpec:
        values:
          - 128
          - 256
          - 512
          - 1024
          - 2048
maxTrialCount: 100
parallelTrialCount: 10
trialJobSpec:
  workerPoolSpecs:
    machineSpec:
      machineType: n1-standard-4
    replicaCount: 1
    pythonPackageSpec:
      executorImageUri: europe-docker.pkg.dev/vertex-ai/training/tf-cpu.2-7:latest
      packageUris: gs://ihr-vertex-pipelines/dist/my_first_ml_model-0.9.tar.gz
      pythonModule: trainer.task
      args:
        - --data-location=/gcs/ihr-vertex-pipelines/data/aclImdb/
        - --job-dir=gs://ihr-vertex-pipelines/job_dir_ht/
        - --parallel-reads
