workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
  replicaCount: 1
  pythonPackageSpec:
    executorImageUri: europe-docker.pkg.dev/vertex-ai/training/tf-cpu.2-7:latest
    packageUris: gs://ihr-vertex-pipelines/dist/my_first_ml_model-0.8.tar.gz
    pythonModule: trainer.task
    args:
      - --data-location=/gcs/ihr-vertex-pipelines/data/aclImdb/
      - --epochs=15
      - --batch-size=128
      - --job-dir=gs://ihr-vertex-pipelines/job_dir/