steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    dir: 'custom_model'
    args: [ "install", "-r", "requirements.txt", "--user" ]
  - name: python
    entrypoint: python
    dir: 'custom_model'
    args: [ "setup.py", "sdist" ]
artifacts:
  objects:
    location: 'gs://ihr-vertex-pipelines/dist/'
    paths: [ 'dist/*.tar.gz' ]